import type { ScenarioState } from "./types";

export const raiseMainsailScenario: ScenarioState = {
  id: "raise-main",
  title: "Raise the mainsail",
  objective:
    "Coordinate crew, keep the yacht head to wind, and raise the mainsail without overloading yourself.",
  timeSec: 0,
  boat: {
    x: 52,
    y: 55,
    headingDeg: 18,
    speedKnots: 2.1,
    angularVelocity: 0,
    momentum: 0.42,
    engine: "idle",
    rudderAngleDeg: 0,
    bowThruster: "off",
    anchor: "stowed",
    mainsail: "down",
  },
  environment: {
    windDirectionDeg: 358,
    windStrengthKnots: 13,
    gustKnots: 17,
    tidalCurrentDirectionDeg: 88,
    tidalCurrentKnots: 0.6,
    visibility: "clear",
  },
  crew: [
    {
      id: "maya",
      name: "Maya",
      role: "helm",
      task: "Awaiting helm instruction",
      experience: 0.7,
      fatigue: 0.12,
      attention: 0.82,
      confidence: 0.72,
      position: "cockpit",
      communicationQuality: 0.82,
    },
    {
      id: "tom",
      name: "Tom",
      role: "mast",
      task: "Ready near halyard",
      experience: 0.45,
      fatigue: 0.2,
      attention: 0.65,
      confidence: 0.54,
      position: "mast",
      communicationQuality: 0.62,
    },
    {
      id: "elena",
      name: "Elena",
      role: "bow",
      task: "Watching traffic and sea room",
      experience: 0.58,
      fatigue: 0.1,
      attention: 0.78,
      confidence: 0.68,
      position: "foredeck",
      communicationQuality: 0.76,
    },
  ],
  score: {
    situationalAwareness: 72,
    workloadDistribution: 64,
    communicationClarity: 68,
    proceduralCompliance: 62,
    safetyMargin: 80,
  },
  events: [
    {
      id: "evt-0",
      timeSec: 0,
      kind: "system",
      message: "Scenario loaded. The mainsail is down, engine idling, wind just off the bow.",
    },
  ],
  commandCount: 0,
  completed: false,
};
